Gradient fill for rectangle(rounded rectangle) shape fixed
windows-toolkit/Lottie-Windows pull request #450
Opened 2021-06-10 23:45 UTC by aborziak-ms

Because of the difference in how gradient fill for rectangles works in **WinComp API** and Lottie, previously it was displayed incorrectly.

**WinComp API** uses top left corner of rectangle as point [0, 0] while Lottie uses middle-middle instead. To account for this difference we need to add **(Rectangle.Size/2)** to Start and End points of gradients. We can't add a constant value since **Rectangle.Size** can also be animated, and if it is animated, we need to use expression animation.

In this change, I added InternalOffset class for rectangle shapes, which propagates information about offset to the gradients and then this offset is applied to Start and End points.

Examples below show how it works now:
#### Lottie-windows old
<img src="https://user-images.githubusercontent.com/83784664/121609884-a9f73900-ca09-11eb-92bf-6459f9b28c6d.gif" width="200px">

#### Lottie web viewer (https://lottiefiles.com/preview)
<img src="https://user-images.githubusercontent.com/83784664/121609864-a19efe00-ca09-11eb-8223-4965b2517f8e.gif" width="200px">

#### Lottie-windows with this PR
<img src="https://user-images.githubusercontent.com/83784664/121609889-ad8ac000-ca09-11eb-85e6-067b5f02f4e4.gif" width="200px">

2021-06-11 16:39 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            // anomate source property first
>anomate [](http://example.com/codeflow?start=15&length=7)

Annotate?

2021-06-11 16:41 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            // create expression that offsets source property by internal offset
>/ create expression that offsets source property by internal offset [](http://example.com/codeflow?start=13&length=67)

I would scub the comments to make them follow the format that the rest of the code has, which is to have then start with a capital letter and a period at the end (where appropriate)

2021-06-11 16:42 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +            // anomate source property first
oh, it should be *an**i**mate* :)

2021-06-11 16:42 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            // anomate source property first
Ah, that makes sense

2021-06-11 16:49 UTC, eliezerpMS commented on source/LottieToWinComp/Rectangles.cs
> +#nullable enable
Just curious, what was the reason for having this just scoped to here?

2021-06-11 16:52 UTC, aborziak-ms commented on source/LottieToWinComp/Rectangles.cs
> +#nullable enable
Ah, yes, it is interesting for me too. Without this Visual Studio complained about `public Expressions.Vector2?` and didn't want to build. I don't know what is special about Expressions.Vector2

2021-06-11 17:43 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +                TranslateVector2AnimatableWithInternalOffset(context, result, nameof(result.StartPoint), startPoint, internalOffset);
I also need to optimize this case, if offset and start/end point are not animated we can use a constant instead of expression

2021-06-11 17:44 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
>              }
This segment is starting to get a bit complicated. I also think for readability how about making this all just 1 function? I think that the two if statements here can be combined (as in we just have the first case with no offset). Then we can call this helper method for both start and end point.

2021-06-11 17:48 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +                ShapeFill.ShapeFillKind.RadialGradient => TranslateRadialGradient(context, (RadialGradientFill)shapeFill, opacity, internalOffset),
nit: this line is getting a bit long. Mind breaking them up into mulitple lines?

2021-06-11 17:53 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
>              }
Yeah, initially that was my plan too. 

Then I noticed that in first two cases we are applying animation to the property without assigning anything, and in third case we are assigning a value. And also we have an optimization so that if value is not assigned then no additional code will be generated (to assign it to default) So I tried to preserve this behavior

But yeah, I will try to find a workaround, I don't like this part too

2021-06-11 17:54 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            string sourcePropertyName = propertyName + "Source";
>propertyName + "Source" [](http://example.com/codeflow?start=40&length=23)

Just curious why add "Soure" for the name?

2021-06-11 17:58 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +            string sourcePropertyName = propertyName + "Source";
If we have an animation for StartPoint (for example) then I'm applying this animation to StartPointSource property, and then applying expression animation to StartPoint property itself, to make it equal to StartPointSource + geometry.Size/2. 

`{Property}Source` is basically a helper-property that stores original animation, and then used inside expression

2021-06-11 17:59 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            WinCompData.Expressions.Vector2 expression = offset.IsAnimated ?
>offset.IsAnimated [](http://example.com/codeflow?start=57&length=17)

If offset.IsAnimated is true then is offset.OffsetExpression ever null?

2021-06-11 18:02 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +            WinCompData.Expressions.Vector2 expression = offset.IsAnimated ?
`IsAnimated` is basically a toggle between `OffsetExpression` and `OffsetValue`, if it **is animated** then `OffsetExpression` is not null, if it **is not animated** then `OffsetValue` is not null. It is guaranteed by having two constructors, one for expression and one for value.

2021-06-11 18:14 UTC, eliezerpMS commented on source/LottieToWinComp/Rectangles.cs
> +            InternalOffset internalOffset = size.IsAnimated ?
>InternalOffset internalOffset = size.IsAnimated ? [](http://example.com/codeflow?start=12&length=49)

I would put a comment here calling why you need to do this and in the other location where you create InternalOffset.

2021-06-11 18:20 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            WinCompData.Expressions.Vector2 expression = offset.IsAnimated ?
I guess I am wondering if OffsetExpression and OffsetValue need to be nullables?

2021-06-11 18:25 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            string sourcePropertyName = propertyName + "Source";
Looking at the other usages of "Properties.Insert..." in the codebase it looks like the names are kept simple. Would it cause an issue to just leave the name as the value of "propertyName"?

2021-06-11 18:29 UTC, eliezerpMS commented on source/LottieToWinComp/Rectangles.cs
> +        public class InternalOffset
>InternalOffset [](http://example.com/codeflow?start=21&length=14)

For naming how about something like "OriginOffset"? I guess I wondering if people might be confused by the term "internal".....

2021-06-11 18:30 UTC, eliezerpMS commented on source/LottieToWinComp/Rectangles.cs
> +            // Use constant value if size if static
>if [](http://example.com/codeflow?start=42&length=2)

is

2021-06-11 18:34 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +            string sourcePropertyName = propertyName + "Source";
I guess we can't do that, since propertyName is the name of reserved property, (e.g. nameof(gradient.StartPoint)) and here I'm just creating auxiliary property (with "Source" at the end) that holds initial animation, so that we can use it inside expression.

**Shortly:** We need to animate "{propertyName}" so that it is equal to **intended animation + offset**, so basically the steps are following:
1. Animate "{propertyName}Source" instead (with original animation)
2. Create expression "{propertyName}Source" + "geometry.Size/2"
3. Animate "{propertyName}" using this expression

2021-06-11 18:48 UTC, eliezerpMS commented on source/LottieToWinComp/Shapes.cs
> +            TranslateAndApplyShapeContextWithTrimOffset(context, shape, reverseDirection, null, 0);
>null [](http://example.com/codeflow?start=90&length=4)

Other shape types don't have this offset issue?

2021-06-11 18:57 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            string sourcePropertyName = propertyName + "Source";
Ok. That sounds fine.

2021-06-11 19:01 UTC, eliezerpMS commented on source/LottieToWinComp/Rectangles.cs
> +#nullable enable
Just curious, what was the error and which project complained?

2021-06-11 19:46 UTC, eliezerpMS requested changes
:clock1:

2021-06-14 16:54 UTC, aborziak-ms commented on source/LottieToWinComp/Rectangles.cs
> +                internalOffset,
Hm, I just noticed that RectangleOrRoundedRectangleGeometry is not CompositionSpriteShape, it is just a helper class. 
We can move offset info to CompositionRectangleGeometry (and CompositionRoundedRectangleGeometry) but not sure if we should add some temporary fields there.

2021-06-14 17:41 UTC, aborziak-ms commented on source/LottieToWinComp/Rectangles.cs
> +#nullable enable
![image](https://user-images.githubusercontent.com/83784664/121934512-3badc180-ccfc-11eb-965c-2935c97ad82b.png)

2021-06-14 17:49 UTC, aborziak-ms commented on source/LottieToWinComp/Shapes.cs
> +            TranslateAndApplyShapeContextWithTrimOffset(context, shape, reverseDirection, null, 0);
Yes, only Rectangle and RoundedRectangle shapes have Offset value.

2021-06-14 17:50 UTC, eliezerpMS commented on source/LottieToWinComp/Rectangles.cs
> +                internalOffset,
Yeah it might be a bit odd to "pollute" Composition object representations with something like that. I guess the next candidate could be to use the ShapeContext.

2021-06-14 18:00 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +            WinCompData.Expressions.Vector2 expression = offset.IsAnimated ?
If we make them non-nullable then we need to initialize them with some default values? I just wanted to use null-ness of them as a flag, `OffsetValue is null` => Animated, `OffsetExpresion is null` => NotAnimated

2021-06-14 18:46 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            var startPointValue = AnimateVector2WithOriginOffsetOrGetValue(context, result, nameof(result.StartPoint), startPoint, originOffset);
>var startPointValue = AnimateVector2WithOriginOffsetOrGetValue(context, result, nameof(result.StartPoint), startPoint, originOffset); [](http://example.com/codeflow?start=12&length=133)

nit: make this into two line like:
var startPointValue = AnimateVector2WithOriginOffsetOrGetValue(
    context,
    result,
    nameof(result.StartPoint),
    startPoint,
    originOffset);

2021-06-14 18:47 UTC, aborziak-ms commented
Ok, so I moved OriginOffset to ShapeLayerContainer, now it looks kind of better in Brushes.cs, Shapes.cs. But now we have this weird line (Rectangles.cs:333) `context.LayerContext.OriginOffset = null;`  because we need to cleanup the offset before exiting this scope.

2021-06-14 18:51 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +        // Returns non-null Sn.Vector2 value if no animation is needed (and no animation was applied).
>Returns non-null Sn.Vector2 value if no animation is needed (and no animation was applied). [](http://example.com/codeflow?start=11&length=91)

I guess a philosophical conversation to have offline: How do you feel about the <summary> syntax for C# functions? It has the "Return" value xml where we could specify things like this. I don't remember why we don't use that in this codebase though...

2021-06-14 18:52 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
>              }
Thanks! I like how it look now much better!

2021-06-14 18:59 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            WinCompData.Expressions.Vector2 expression = offset.IsAnimated ?
Yeah I guess I was thinking that you already know the flag value from the contructor and it does not change. so you could just have "public bool IsAnimated { get; }". Mostly I am making this suggesting because I feel that the code that uses OriginOffset does not really make use of the nullable nature of OffsetValue and OffsetExpression.

2021-06-14 19:03 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +            var startPointValue = AnimateVector2WithOriginOffsetOrGetValue(context, result, nameof(result.StartPoint), startPoint, originOffset);
Now without originOffset parameter line is shorter. It is about the length of other lines in the file, now it is ok without newlines?

2021-06-14 19:20 UTC, eliezerpMS commented on source/LottieToWinComp/Rectangles.cs
> +#nullable enable
Looks like some other files also have this warning. I guess we can discuss offline about using "#nullable enable" or not or if we want enable it project wide.

2021-06-14 20:08 UTC, eliezerpMS commented
In TranslateAndApplyShapeContextWithTrimOffset in Shapes.cs before you call "Brushes.TranslateAndApplyStroke(context, context.Stroke, shape, context.Opacity);" Do you need to call do the clearing out of OriginOffset here instead? It looks like TranslateAndApplyStroke can hit the linear gradient code but I assume it does not need the offset stuff factored in. If you do put the clearing here then also put a comment about how the offset is only needed for shape fills.

---
In reply to: [860911730](https://github.com/windows-toolkit/Lottie-Windows/pull/450#issuecomment-860911730) [](http://example.com/codeflow?ancestors=860911730,860911730)

2021-06-14 20:11 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +            var startPointValue = AnimateVector2WithOriginOffsetOrGetValue(context, result, nameof(result.StartPoint), startPoint, originOffset);
Yep this is fine.

2021-06-14 20:24 UTC, aborziak-ms commented
> In TranslateAndApplyShapeContextWithTrimOffset in Shapes.cs before you call "Brushes.TranslateAndApplyStroke(context, context.Stroke, shape, context.Opacity);" Do you need to call do the clearing out of OriginOffset here instead? It looks like TranslateAndApplyStroke can hit the linear gradient code but I assume it does not need the offset stuff factored in. If you do put the clearing here then also put a comment about how the offset is only needed for shape fills.

Agree, done

2021-06-14 20:30 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +            WinCompData.Expressions.Vector2 expression = offset.IsAnimated ?
I see, yeah, agree. Done

2021-06-14 20:31 UTC, aborziak-ms commented on source/LottieToWinComp/Brushes.cs
> +        // Returns non-null Sn.Vector2 value if no animation is needed (and no animation was applied).
You mean this?
![image](https://user-images.githubusercontent.com/83784664/121955477-df0ad080-cd14-11eb-8cfe-04fa93470637.png)

2021-06-14 21:23 UTC, eliezerpMS commented on source/LottieToWinComp/Brushes.cs
> +        // Returns non-null Sn.Vector2 value if no animation is needed (and no animation was applied).
Yep. Not for this PR but it would be interesting to discuss with you (maybe during a sync meeting) about where if at this format should be used.

2021-06-14 21:25 UTC, eliezerpMS approved these changes
:shipit:

2021-06-14 23:48 UTC, merged